apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-service
  template:
    metadata:
      labels:
        app: business-service
    spec:
      containers:
        - name: business-service
          image: adilkatok/business-service:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: business-service
spec:
  selector:
    app: business-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082