name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JARs (all services)
        run: |
          ./auth-service/gradlew -p auth-service bootJar
          ./business-service/gradlew -p business-service bootJar
          ./api-gateway/gradlew -p api-gateway bootJar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push auth-service
        uses: docker/build-push-action@v5
        with:
          context: ./auth-service
          file: ./auth-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest

      - name: Build and push business-service
        uses: docker/build-push-action@v5
        with:
          context: ./business-service
          file: ./business-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/business-service:latest

      - name: Build and push api-gateway
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest